Finish shellcheck cleanup.

diff --git a/test/fi-to-fi b/test/fi-to-fi
--- a/test/fi-to-fi
+++ b/test/fi-to-fi
@@ -42,7 +42,7 @@ do
 	g) extract=True ;  view=True; stream=False ; cleanup=False ;;
 	n) extract=True ;  view=False; stream=False ; cleanup=False ;;
         o) extract=False ; view=False; stream=True  ; cleanup=False ;;
-	*) echo "fi-to-fi: unknown flag $opt" >&2; exit 1;;
+	*) echo "$0: unknown flag $opt" >&2; exit 1;;
     esac
 done
 # shellcheck disable=SC2004
@@ -55,13 +55,13 @@ testrepo=${1:-${tmpdir}/test-repo$$}
 if [ $extract = True ]
 then
     rm -fr "$testrepo"; mkdir "$testrepo"
-    (cd "$testrepo" >/dev/null || (echo "cd failed" >&2; exit 1); git init --quiet; git fast-import --quiet; git checkout) 
+    (cd "$testrepo" >/dev/null || (echo "$0: cd failed" >&2; exit 1); git init --quiet; git fast-import --quiet; git checkout) 
 fi
 
 # Should we view the repo?
 if [ $view = True ]
 then
-    (cd "$testrepo" >/dev/null || (echo "cd failed" >&2; exit 1); gitk --all --tags)
+    (cd "$testrepo" >/dev/null || (echo "$0: cd failed" >&2; exit 1); gitk --all --tags)
 fi
 
 # Should we stream the repo?
diff --git a/test/svn-to-svn b/test/svn-to-svn
--- a/test/svn-to-svn
+++ b/test/svn-to-svn
@@ -89,7 +89,7 @@ do
 	q) quiet=-q ;;
 	r) limit="$OPTARG" ;;
 	l) log="log $OPTARG" ;;
-	*) echo "svn-to-svn: unknown flag $opt" >&2; exit 1;;
+	*) echo "$0: unknown flag $opt" >&2; exit 1;;
     esac
 done
 # shellcheck disable=SC2004
@@ -170,7 +170,7 @@ fi
 # Should we view the repo?
 if [ "$view" = T ]
 then
-    (cd "$testrepo" >/dev/null || (echo "cd failed" >&2; exit 1); ${REPOSURGEON:-reposurgeon} "${log}" "${TESTOPT}" "read ." "prefer git" "rebuild ${tmpdir}/testrepo$$"; cd "${tmpdir}/testrepo$$" 2>/dev/null || (echo "cd failed"; exit 1); gitk --all --tags)
+    (cd "$testrepo" >/dev/null || (echo "$0: cd failed" >&2; exit 1); ${REPOSURGEON:-reposurgeon} "${log}" "${TESTOPT}" "read ." "prefer git" "rebuild ${tmpdir}/testrepo$$"; cd "${tmpdir}/testrepo$$" 2>/dev/null || (echo "$0: cd failed"; exit 1); gitk --all --tags)
 fi
 
 # Should we dump a conversion of the repo as a fast-import stream?
