Shellcheck cleanup.

diff --git a/test/hg-bb-alt-test b/test/hg-bb-alt-test
--- a/test/hg-bb-alt-test
+++ b/test/hg-bb-alt-test
@@ -14,31 +14,33 @@
 # The REPOSURGEON environment variable can be used to substitute in a
 # different implementation.
 
-cd "$(readlink -f "$(dirname $0)")"
+# shellcheck disable=SC2086
+cd "$(readlink -f "$(dirname $0)")" || ( echo "$0: cd failed"; exit 1 )
+# shellcheck disable=SC1091
 . ./common-setup.sh
 
 # Required because $PWD seems to be undefined in Gitlab's CI environment
-BIN=`realpath ..`
+BIN=$(realpath ..)
 
 build=True
 stream=True
 cleanup=True
-verbose=0
 
 pecho() { printf %s\\n "$*"; }
 log() { pecho "$@"; }
-error() { log "ERROR: $@" >&2; }
+error() { log "ERROR: $*" >&2; }
 fatal() { error "$@"; exit 1; }
-try() { "$@" || fatal "'$@' failed"; }
+try() { "$@" || fatal "'$*' failed"; }
 
-while getopts nrv opt
+while getopts nr opt
 do
     case $opt in
     n) build=True; stream=False ; cleanup=False ;;
     r) build=False; stream=True  ; cleanup=False ;;
-    v) verbose=$IOPTARG;;
+    *) echo "$0: unknown option $opt"; exit 1;;
     esac
 done
+# shellcheck disable=SC2004
 shift $(($OPTIND - 1))
 
 testrepo=${1:-/tmp/test-repo$$}
@@ -50,8 +52,8 @@ if [ $build = True ]
 then
     # Build hg test repo with multiple hg branches
     try rm -fr $testrepo
-    try hg init $testrepo || exit 1
-    try cd $testrepo >/dev/null
+    try hg init "$testrepo" || exit 1
+    try cd "$testrepo" >/dev/null
     # The weird --date incantation in the hg commits is to ensure that the commit
     # timestamps match those in the .fi file; the 18000 is because hg wants the time zone
     # offset in seconds west of UTC, for what reason I know not--I know there are weird
@@ -65,7 +67,7 @@ then
         try hg add testfile3 >/dev/null
         try hg commit --user "$USER" --date "1456976408 18000" -m "Commit test file 3." >/dev/null
         try hg update -r 0 >/dev/null
-        try cd $testrepo >/dev/null     # Workaround for error getting current working directory
+        try cd "$testrepo" >/dev/null     # Workaround for error getting current working directory
         try hg branch test >/dev/null
         try echo "Test file 2." > testfile2
         try hg add testfile2 >/dev/null
@@ -78,7 +80,7 @@ fi
 # Should we stream the repo?
 if [ $stream = True ]
 then
-    try ${BIN}/${REPOSURGEON:-reposurgeon} ${BUILDOPT} ${TESTOPT} "set quiet" "read $testrepo" "sourcetype git" "write -"
+    try "${BIN}/${REPOSURGEON:-reposurgeon}" ${BUILDOPT} ${TESTOPT} "set quiet" "read $testrepo" "sourcetype git" "write -"
 fi
 
 # Should we clean up the test directory
diff --git a/test/hg-be-test b/test/hg-be-test
--- a/test/hg-be-test
+++ b/test/hg-be-test
@@ -11,30 +11,31 @@
 # The REPOSURGEON environment variable can be used to substitute in a
 # different implementation.
 
+# shellcheck disable=SC1091
 . ./common-setup.sh
 
 # Required because $PWD seems to be undefined in Gitlab's CI environment
-BIN=`realpath ..`
+BIN=$(realpath ..)
 
 build=True
 stream=True
 cleanup=True
-verbose=0
 
 pecho() { printf %s\\n "$*"; }
 log() { pecho "$@"; }
-error() { log "ERROR: $@" >&2; }
+error() { log "ERROR: $*" >&2; }
 fatal() { error "$@"; exit 1; }
-try() { "$@" || fatal "'$@' failed"; }
+try() { "$@" || fatal "'$*' failed"; }
 
-while getopts nrv: opt
+while getopts nr opt
 do
     case $opt in
     n) build=True; stream=False ; cleanup=False ;;
     r) build=False; stream=True  ; cleanup=False ;;
-    v) verbose=$OPTARG;;
+    *) echo "$0: unknown option $opt"; exit 1;;
     esac
 done
+# shellcheck disable=SC2004
 shift $(($OPTIND - 1))
 
 testrepo=${1:-/tmp/test-repo$$}
@@ -45,9 +46,9 @@ USER='"J. Random Hacker" <jrh@foobar.com>'
 if [ $build = True ]
 then
     # Build hg test repo with multiple hg branches
-    try rm -fr $testrepo
-    try hg init $testrepo || exit 1
-    try cd $testrepo >/dev/null
+    try rm -fr "$testrepo"
+    try hg init "$testrepo" || exit 1
+    try cd "$testrepo" >/dev/null
     # The weird --date incantation in the hg commits is to ensure that the commit
     # timestamps match those in the .fi file; the 18000 is because hg wants the time zone
     # offset in seconds west of UTC, for what reason I know not--I know there are weird
@@ -62,7 +63,7 @@ then
         try hg add testfile2 >/dev/null
         try hg commit --user "$USER" --date "1456976408 18000" -m "Commit test file 2." >/dev/null
         try hg update default >/dev/null
-        try cd $testrepo >/dev/null
+        try cd "$testrepo" >/dev/null
         try echo "Test file 3." > testfile3
         try hg add testfile3 >/dev/null
         try hg commit --user "$USER" --date "1456976475 18000" -m "Commit test file 3." >/dev/null
@@ -73,11 +74,12 @@ fi
 # Should we stream the repo?
 if [ $stream = True ]
 then
-    try ${BIN}/${REPOSURGEON:-reposurgeon} ${BUILDOPT} ${TESTOPT} "set quiet" "read $testrepo" "sourcetype git" "write -"
+    # shellcheck disable=SC2086
+    try "${BIN}/${REPOSURGEON:-reposurgeon}" ${BUILDOPT} ${TESTOPT} "set quiet" "read $testrepo" "sourcetype git" "write -"
 fi
 
 # Should we clean up the test directory
 if [ $cleanup = True ]
 then
-    try rm -fr $testrepo
+    try rm -fr "$testrepo"
 fi
diff --git a/test/hg-be5-test b/test/hg-be5-test
--- a/test/hg-be5-test
+++ b/test/hg-be5-test
@@ -11,31 +11,33 @@
 # The REPOSURGEON environment variable can be used to substitute in a
 # different implementation.
 
-cd "$(readlink -f "$(dirname $0)")"
+# shellcheck disable=SC2086
+cd "$(readlink -f "$(dirname $0)")" || ( echo "$0: cd failed"; exit 1 )
+# shellcheck disable=SC1091
 . ./common-setup.sh
 
 # Required because $PWD seems to be undefined in Gitlab's CI environment
-BIN=`realpath ..`
+BIN=$(realpath ..)
 
 build=True
 stream=True
 cleanup=True
-verbose=0
 
 pecho() { printf %s\\n "$*"; }
 log() { pecho "$@"; }
-error() { log "ERROR: $@" >&2; }
+error() { log "ERROR: $*" >&2; }
 fatal() { error "$@"; exit 1; }
-try() { "$@" || fatal "'$@' failed"; }
+try() { "$@" || fatal "'$*' failed"; }
 
-while getopts nrv: opt
+while getopts nr opt
 do
     case $opt in
     n) build=True; stream=False ; cleanup=False ;;
     r) build=False; stream=True  ; cleanup=False ;;
-    v) verbose=$OPTARG;;
+    *) echo "$0: unknown option $opt"; exit 1;;
     esac
 done
+# shellcheck disable=SC2004
 shift $(($OPTIND - 1))
 
 testrepo=${1:-/tmp/test-repo$$}
@@ -47,8 +49,8 @@ if [ $build = True ]
 then
     # Build hg test repo with multiple hg branches
     try rm -fr $testrepo
-    try hg init $testrepo || exit 1
-    try cd $testrepo >/dev/null
+    try hg init "$testrepo" || exit 1
+    try cd "$testrepo" >/dev/null
     # The weird --date incantation in the hg commits is to ensure that the commit
     # timestamps match those in the .fi file; the 18000 is because hg wants the time zone
     # offset in seconds west of UTC, for what reason I know not--I know there are weird
@@ -62,23 +64,23 @@ then
         try hg add testfile3 >/dev/null
         try hg commit --user "$USER" --date "1456976408 18000" -m "Commit test file 3." >/dev/null
         try hg update -r 0 >/dev/null
-        try cd $testrepo >/dev/null     # Workaround for error getting current working directory
+        try cd "$testrepo" >/dev/null     # Workaround for error getting current working directory
         try hg branch test >/dev/null
         try echo "Test file 2." > testfile2
         try hg add testfile2 >/dev/null
         try hg commit --user "$USER" --date "1456976475 18000" -m "Commit test file 2." >/dev/null
         try hg update default >/dev/null
-        try cd $testrepo >/dev/null     # Workaround for error getting current working directory
+        try cd "$testrepo" >/dev/null     # Workaround for error getting current working directory
         try hg merge test >/dev/null
         try hg commit --user "$USER" --date "1456976606 18000" -m "Merge test branch." >/dev/null
         try hg update test >/dev/null
-        try cd $testrepo >/dev/null     # Workaround for error getting current working directory
+        try cd "$testrepo" >/dev/null     # Workaround for error getting current working directory
         try echo "Test file 4." > testfile4
         try hg add testfile4 >/dev/null
         try hg commit --user "$USER" --date "1456976715 18000" -m "Commit test file 4." >/dev/null
         try hg tag --local 1.0a >/dev/null
         try hg update default >/dev/null
-        try cd $testrepo >/dev/null     # Workaround for error getting current working directory
+        try cd "$testrepo" >/dev/null     # Workaround for error getting current working directory
         try echo "Test file 5." > testfile5
         try hg add testfile5 >/dev/null
         try hg commit --user "$USER" --date "1456976798 18000" -m "Commit test file 5." >/dev/null
@@ -86,7 +88,7 @@ then
         try echo "Second line." >> testfile5
         try hg commit --user "$USER" --date "1457895329 14400" -m "Add line to test file 5." >/dev/null
         try hg update test >/dev/null
-        try cd $testrepo >/dev/null     # Workaround for error getting current working directory
+        try cd "$testrepo" >/dev/null     # Workaround for error getting current working directory
         try echo "Second line." >> testfile4
         try hg commit --user "$USER" --date "1457895350 14400" -m "Add line to test file 4." >/dev/null
     ) || exit 1
@@ -96,7 +98,8 @@ fi
 # Should we stream the repo?
 if [ $stream = True ]
 then
-    try ${BIN}/${REPOSURGEON:-reposurgeon} ${BUILDOPT} ${TESTOPT} "set quiet" "read $testrepo" "sourcetype git" "write -"
+    # shellcheck disable=SC2086
+    try "${BIN}/${REPOSURGEON:-reposurgeon}" ${BUILDOPT} ${TESTOPT} "set quiet" "read $testrepo" "sourcetype git" "write -"
 fi
 
 # Should we clean up the test directory
diff --git a/test/hg-bt2-test b/test/hg-bt2-test
--- a/test/hg-bt2-test
+++ b/test/hg-bt2-test
@@ -9,10 +9,11 @@
 # The REPOSURGEON environment variable can be used to substitute in a
 # different implementation.
 
+# shellcheck disable=SC1091
 . ./common-setup.sh
 
 # Required because $PWD seems to be undefined in Gitlab's CI environment
-BIN=`realpath ..`
+BIN=$(realpath ..)
 
 build=True
 stream=True
@@ -20,17 +21,19 @@ cleanup=True
 
 pecho() { printf %s\\n "$*"; }
 log() { pecho "$@"; }
-error() { log "ERROR: $@" >&2; }
+error() { log "ERROR: $*" >&2; }
 fatal() { error "$@"; exit 1; }
-try() { "$@" || fatal "'$@' failed"; }
+try() { "$@" || fatal "'$*' failed"; }
 
 while getopts nr opt
 do
     case $opt in
     n) build=True; stream=False ; cleanup=False ;;
     r) build=False; stream=True  ; cleanup=False ;;
+    *) echo "$0: unknown option $opt"; exit 1;;
     esac
 done
+# shellcheck disable=SC2004
 shift $(($OPTIND - 1))
 
 testrepo=${1:-/tmp/test-repo$$}
@@ -41,9 +44,9 @@ USER='"J. Random Hacker" <jrh@foobar.com>'
 if [ $build = True ]
 then
     # Build hg test repo with multiple hg branches
-    try rm -fr $testrepo
-    try hg init $testrepo || exit 1
-    try cd $testrepo >/dev/null
+    try rm -fr "$testrepo"
+    try hg init "$testrepo" || exit 1
+    try cd "$testrepo" >/dev/null
     # The weird --date incantation in the hg commits is to ensure that the commit
     # timestamps match those in the .fi file; the 18000 is because hg wants the time zone
     # offset in seconds west of UTC, for what reason I know not--I know there are weird
@@ -58,13 +61,13 @@ then
         try hg commit --user "$USER" --date "1456976408 18000" -m "Commit test file 3." >/dev/null
         try hg tag --local before >/dev/null
         try hg update -r 0 >/dev/null
-        try cd $testrepo >/dev/null     # Workaround for error getting current working directory
+        try cd "$testrepo" >/dev/null     # Workaround for error getting current working directory
         try echo "Test file 2." > testfile2
         try hg add testfile2 >/dev/null
         try hg commit --user "$USER" --date "1456976475 18000" -m "Commit test file 2." >/dev/null
         try hg tag --local after >/dev/null
         try hg update before >/dev/null
-        try cd $testrepo >/dev/null     # Workaround for error getting current working directory
+        try cd "$testrepo" >/dev/null     # Workaround for error getting current working directory
         try echo "Second line." >> testfile3
         try hg commit --user "$USER" --date "1456976542 18000" -m "Add line to test file 3." >/dev/null
     ) || exit 1
@@ -74,11 +77,12 @@ fi
 # Should we stream the repo?
 if [ $stream = True ]
 then
-    try ${BIN}/${REPOSURGEON:-reposurgeon} ${BUILDOPT} ${TESTOPT} "read $testrepo" "sourcetype git" "write -"
+    # shellcheck disable=SC2086
+    try "${BIN}/${REPOSURGEON:-reposurgeon}" ${BUILDOPT} ${TESTOPT} "read $testrepo" "sourcetype git" "write -"
 fi
 
 # Should we clean up the test directory
 if [ $cleanup = True ]
 then
-    try rm -fr $testrepo
+    try rm -fr "$testrepo"
 fi
