Fix propagation of executable bits across SVN branch copies.
Bug was formerly masked by a misquote in the tests for SVN loading,
also fixed in this patch.

All tests pass, but there's one minor glitch left; the correctness test
for executable.svn issues output but should not.

diff --git a/test/Makefile b/test/Makefile
--- a/test/Makefile
+++ b/test/Makefile
@@ -358,10 +358,7 @@ liftcheck-regress:
 		for test in $(SVNCLEAN); \
 		do \
 		    { $(ECHO) -n "  $${test}.svn"; grep --text '^ ##' $${test}.svn || echo ' ## (no description)'; } >&2; \
-		if test ! -z `liftcheck $${test}` ; \
-		then \
-			echo echo "*** Nonzero return status on $${test}!"; exit 1; \
-		fi \
+		    liftcheck $${test} || { echo "*** Failed on $${test}!"; exit 1; } \
 		done \
 	else \
 		echo "     Skipped, either git or svn is missing"; \
