In the generated conversion makefile, sub in source and target VCS types.

diff --git a/repotool b/repotool
--- a/repotool
+++ b/repotool
@@ -28,26 +28,47 @@ initialize)
 	echo "repotool: a project lift file already exists here."
 	exit 1
     fi
+    shift
+    if [ -z "$1" ]
+    then
+	/bin/echo -n "repotool: what VCS do you want to convert from? "
+	read source_vcs
+    else
+	source_vcs=$1
+    fi
+    case $source_vcs in
+	cvs|svn|git|bzr|hg|darcs) ;;
+	*) echo "repotool: unknown source VCS type ${source_vcs}"; exit 1 ;;
+    esac
+    shift
+    if [ -z "$1" ]
+    then
+	/bin/echo -n "repotool: what VCS do you want to convert to? "
+	read target_vcs
+    else
+	target_vcs=$1
+    fi
+    case $target_vcs in
+	cvs|svn|git|bzr|hg|darcs) ;;
+	*) echo "repotool: unknown target VCS type ${target_vcs}"; exit 1 ;;
+    esac 
     echo "repotool: generating Makefile, some variables in it need to be set."
     cat >Makefile <<EOF
 # Makefile for $project conversion using reposurgeon
 #
 # Steps to using this:
 # 1. Make sure reposurgeon and repotool are on your \$PATH.
-# 2. Set SOURCE_VCS to svn, cvs, git, hg, bzr, or darcs.
-# 3. Set TARGET_VCS to git, hg, bzr, or darcs.
-# 4. For svn, set REMOTE_URL to point at the remote repository
+# 2. For svn, set REMOTE_URL to point at the remote repository
 #    you want to convert.
-# 5. For cvs, set CVS_HOST to the repo hostname and CVS_MODULE to the module,
+# 3. For cvs, set CVS_HOST to the repo hostname and CVS_MODULE to the module,
 #    then uncomment the line that builds REMOTE_URL 
 #    Note: for CVS hosts other than Sourceforge or Savannah you will need to 
 #    include the path to the CVS modules directory after the hostname.
-# 6. Run 'make stubmap' to create a stub author map.
-# 7. (Optional) set REPOSURGEON to point at a faster cython build of the tool.
-# 8. (Optional) use a text editor to explicitly substitute
-#     \$(SOURCE_VCS), and \$(TARGET_VCS), then remove those definitions.  This
-#     will make the productions much easier to read.
-# 9. Run 'make' to build a converted repository.
+# 4. Set any required read options, such as --user-ignores or --nobranch,
+#    by setting READ_OPTIONS.
+# 5. Run 'make stubmap' to create a stub author map.
+# 6. (Optional) set REPOSURGEON to point at a faster cython build of the tool.
+# 7. Run 'make' to build a converted repository.
 #
 # The reason both first- and second-stage stream files are generated is that,
 # especially with Subversion, making the first-stage stream file is often
@@ -62,8 +83,6 @@ initialize)
 # to check your work.
 #
 
-SOURCE_VCS = svn
-TARGET_VCS = git
 EXTRAS = 
 REMOTE_URL = svn://svn.debian.org/${project}
 #REMOTE_URL = https://${project}.googlecode.com/svn/
@@ -71,37 +90,35 @@ CVS_HOST = cvs.sourceforge.net
 #CVS_HOST = cvs.savannah.gnu.org
 CVS_MODULE = ${project}
 #REMOTE_URL = cvs://\$(CVS_HOST)/${project}#\$(CVS_MODULE)
+READ_OPTIONS =
 VERBOSITY = "verbose 1"
 REPOSURGEON = reposurgeon
 
 # Configuration ends here
 
 .PHONY: local-clobber remote-clobber gitk gc compare clean dist stubmap
-# Tell make not to auto-remove tag directories, because it only tries rm and hence fails
-.PRECIOUS: ${project}-%-checkout ${project}-%-\$(TARGET_VCS)
+# Tell make not to auto-remove tag directories, because it only tries rm 
+# and hence fails
+.PRECIOUS: ${project}-%-checkout ${project}-%-${target_vcs}
 
-default: ${project}-\$(TARGET_VCS)
+default: ${project}-${target_vcs}
 
 # Build the converted repo from the second-stage fast-import stream
-${project}-\$(TARGET_VCS): ${project}.fi
-	rm -fr ${project}-\$(TARGET_VCS); \$(REPOSURGEON) "read <${project}.fi" "prefer \$(TARGET_VCS)" "rebuild ${project}-\$(TARGET_VCS)"
+${project}-${target_vcs}: ${project}.fi
+	rm -fr ${project}-${target_vcs}; \$(REPOSURGEON) "read <${project}.fi" "prefer ${target_vcs}" "rebuild ${project}-${target_vcs}"
 
 # Build the second-stage fast-import stream from the first-stage stream dump
-${project}.fi: ${project}.\$(SOURCE_VCS) ${project}.opts ${project}.lift ${project}.map \$(EXTRAS)
-	\$(REPOSURGEON) \$(VERBOSITY) "script ${project}.opts" "read <${project}.\$(SOURCE_VCS)" "authors read <${project}.map" "sourcetype \$(SOURCE_VCS)" "prefer git" "script ${project}.lift" "legacy write >${project}.fo" "write >${project}.fi"
+${project}.fi: ${project}.${source_vcs} ${project}.opts ${project}.lift ${project}.map \$(EXTRAS)
+	\$(REPOSURGEON) \$(VERBOSITY) "script ${project}.opts" "read \$(READ_OPTIONS) <${project}.${source_vcs}" "authors read <${project}.map" "sourcetype ${source_vcs}" "prefer git" "script ${project}.lift" "legacy write >${project}.fo" "write >${project}.fi"
 
 # Build the first-stage stream dump from the local mirror
-${project}.\$(SOURCE_VCS): ${project}-mirror
+${project}.${source_vcs}: ${project}-mirror
 	repotool mirror ${project}-mirror
-	(cd ${project}-mirror/ >/dev/null; repotool export) >${project}.\$(SOURCE_VCS)
+	(cd ${project}-mirror/ >/dev/null; repotool export) >${project}.${source_vcs}
 
 # Build a local mirror of the remote repository
 ${project}-mirror:
 	repotool mirror \$(REMOTE_URL) ${project}-mirror
-
-#  Get a list of tags from the project mirror
-${project}-tags.txt: ${project}-mirror
-	cd ${project}-mirror >/dev/null; repotool tags
 
 # Make a local checkout of the source mirror for inspection
 ${project}-checkout: ${project}-mirror
@@ -113,28 +130,28 @@ ${project}-%-checkout: ${project}-mirror
 
 # Force rebuild of first-stage stream from the local mirror on the next make
 local-clobber: clean
-	rm -fr ${project}.fi ${project}-\$(TARGET_VCS) *~ .rs* ${project}-conversion.tar.gz ${project}-*-\$(TARGET_VCS)
+	rm -fr ${project}.fi ${project}-${target_vcs} *~ .rs* ${project}-conversion.tar.gz ${project}-*-${target_vcs}
 
 # Force full rebuild from the remote repo on the next make.
 remote-clobber: local-clobber
-	rm -fr ${project}.\$(SOURCE_VCS) ${project}-mirror ${project}-checkout ${project}-*-checkout
+	rm -fr ${project}.${source_vcs} ${project}-mirror ${project}-checkout ${project}-*-checkout
 
 # Get the (empty) state of the author mapping from the first-stage stream
-stubmap: ${project}.\$(SOURCE_VCS)
-	\$(REPOSURGEON) "read <${project}.\$(SOURCE_VCS)" "authors write >${project}.map"
+stubmap: ${project}.${source_vcs}
+	\$(REPOSURGEON) "read <${project}.${source_vcs}" "authors write >${project}.map"
 
 # Compare the histories of the unconverted and converted repositories at head
 # and all tags.
-EXCLUDE = -x CVS -x .\$(SOURCE_VCS) -x .\$(TARGET_VCS)
-EXCLUDE += -x .\$(SOURCE_VCS)ignore -x .\$(TARGET_VCS)ignore
+EXCLUDE = -x CVS -x .${source_vcs} -x .${target_vcs}
+EXCLUDE += -x .${source_vcs}ignore -x .${target_vcs}ignore
 headcompare:
-	repotool compare \$(EXCLUDE) ${project}-checkout ${project}-\$(TARGET_VCS)
+	repotool compare \$(EXCLUDE) ${project}-checkout ${project}-${target_vcs}
 tagscompare:
-	repotool compare-tags \$(EXCLUDE) ${project}-checkout ${project}-\$(TARGET_VCS)
+	repotool compare-tags \$(EXCLUDE) ${project}-checkout ${project}-${target_vcs}
 
 # General cleanup and utility
 clean:
-	rm -fr *~ .rs* ${project}-conversion.tar.gz *.\$(SOURCE_VCS) *.fi *.fo
+	rm -fr *~ .rs* ${project}-conversion.tar.gz *.${source_vcs} *.fi *.fo
 
 # Bundle up the conversion metadata for shipping
 SOURCES = Makefile ${project}.lift ${project}.map \$(EXTRAS)
@@ -142,12 +159,14 @@ ${project}-conversion.tar.gz: \$(SOURCES)
 	tar --dereference --transform 's:^:${project}-conversion/:' -czvf ${project}-conversion.tar.gz \$(SOURCES)
 
 dist: ${project}-conversion.tar.gz
+EOF
+    if [ $target_vcs = git ]
+    then
+	cat >>Makefile <<EOF
 
 #
 # The following productions are git-specific
 #
-
-ifeq (\$(TARGET_VCS),git)
 
 # Browse the generated git repository
 gitk: ${project}-git
@@ -158,9 +177,8 @@ gitk: ${project}-git
 # tuned for very large repositories.
 gc: ${project}-git
 	cd ${project}-git; time git -c pack.threads=1 repack -AdF --window=1250 --depth=250
-
-endif
 EOF
+    fi
     echo "# Pre-read options for reposurgeon go here." >${project}.opts
     echo "# Lift commands for ${project}" >${project}.lift
     ;;
