Simplify the polotting code in repobench.

diff --git a/repobench b/repobench
--- a/repobench
+++ b/repobench
@@ -55,54 +55,33 @@ fi
 if [ $display = yes ]
 then
     datfile=${datfile:-$1}
+    if [ ! -f "$datfile" ]
+    then
+	echo "File ${datfile} is missing." >&2
+	exit 1
+    fi
     case $style in
-	runtime)
-	    cat >/tmp/plotme$$ <<EOF
-set key top lmargin
-set xlabel "number of SVN revisions read in by reposurgeon"
-set ylabel "$style"
-f(x) = a*x + b
-g(x) = c*x**2 + d*x + e
-fit f(x) file using 1:2 via a,b
-fit g(x) file using 1:2 via c,d,e
-plot file u 1:2 title "memory usage" lw 2, \
-     f(x) title "linear fit" lw 2, \
-     g(x) title "quadratic fit" lw 2
-EOF
-	    ;;
-	heap)
-	    cat >/tmp/plotme$$ <<EOF
-set key top lmargin
-set xlabel "number of SVN revisions read in by reposurgeon"
-set ylabel "$style"
-f(x) = a*x + b
-g(x) = c*x**2 + d*x + e
-fit f(x) file using 1:3 via a,b
-fit g(x) file using 1:3 via c,d,e
-plot file u 1:3 title "memory (current heap size)" lw 2, \
-     f(x) title "linear fit" lw 2, \
-     g(x) title "quadratic fit" lw 2
-EOF
-	    ;;
-	highwater)
-	    cat >/tmp/plotme$$ <<EOF
-set key top lmargin
-set xlabel "number of SVN revisions read in by reposurgeon"
-set ylabel "$style"
-f(x) = a*x + b
-g(x) = c*x**2 + d*x + e
-fit f(x) file using 1:4 via a,b
-fit g(x) file using 1:4 via c,d,e
-plot file u 1:4 title "memory (high water mark)" lw 2, \
-     f(x) title "linear fit" lw 2, \
-     g(x) title "quadratic fit" lw 2
-EOF
-	    ;;
+	runtime) idx=2; title="Running time";;
+	heap) idx=3; title="Memory (heap allocation)";;
+	highwater) idx=4; title="Memory (total)";;
 	*)
 	    echo "Unknown plot type $style" >&2
 	    exit 1
 	    ;;
     esac
+	
+    cat >/tmp/plotme$$ <<EOF
+set key top lmargin
+set xlabel "number of revisions read in by reposurgeon"
+set ylabel "$style"
+f(x) = a*x + b
+g(x) = c*x**2 + d*x + e
+fit f(x) file using 1:$idx via a,b
+fit g(x) file using 1:$idx via c,d,e
+plot file u 1:2 title "$title" lw 2, \
+     f(x) title "linear fit" lw 2, \
+     g(x) title "quadratic fit" lw 2
+EOF
 
     # The actual plotting
     if [ $svg = yes ]
