First cut at compareall operation in repotool.

diff --git a/repotool b/repotool
--- a/repotool
+++ b/repotool
@@ -195,11 +195,32 @@ compare)
     cd $repo1; repotool checkout /tmp/source $rev
     cd $repo2; repotool checkout /tmp/target $rev
     cd $here
-    diff --ignore-matching-lines=' @(#) ' --ignore-matching-lines='$Id.*$' -u -r /tmp/source /tmp/target | sed \
+    diff --ignore-matching-lines=' @(#) ' --ignore-matching-lines='$Id.*$' --ignore-matching-lines='$Header.*$' -u -r /tmp/source /tmp/target | sed \
 			-e '/Only in .tmp./s//Only in /' \
 			-e '/: /s::/:' \
 			-e '/source./s//source: /' \
 		        -e '/target./s//target: /'
+    ;;
+compareall)
+    repo1=`realpath $1`
+    shift
+    repo2=`realpath $1`
+    shift
+    rev=$1
+    if [ -z "$repo1" -o -z "$repo2" ]
+    then
+	echo "repotool: two repositories are required for comparison."
+	exit 1
+    fi
+    here=$PWD
+    cd $repo1; tags=`git tag -l`
+    cd $here
+    for tag in $tags
+    do
+	echo "----------------------------------------------------------------"
+	echo "${tag}:"
+	repotool compare $repo1 $repo2 $tag
+    done
     ;;
 *)
     echo "repotool: unknown action '$operation'."
